### ISSUE TITLE
[`firestartr-workflows`] Workflows for build and dispatch docker images

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#98]
### Motivation
We need to have the necessary workflows to build and dispatch new images available from the code repos to the state repos

### Acceptance criteria
repo workflows
- [x] build-docker-snapshots
- [x] build-docker-pre-releases
- [x] build-docker-releases 
- [x] make-dispatches
- [x] trigger-dispatch-on-snapshot / pre-release / release

reusable workflows

actions

```[tasklist]
### firestarter-workflows
- [ ] https://github.com/prefapp/firestarter-workflows/issues/70
- [ ] https://github.com/prefapp/firestarter-workflows/issues/96
- [ ] https://github.com/prefapp/firestarter-workflows/issues/95
- [ ] https://github.com/prefapp/firestarter-workflows/issues/94
```

```[tasklist]
### action-make-state-repo-dispatches
- [ ] https://github.com/prefapp/action-make-state-repos-dispatches/issues/26
- [ ] https://github.com/prefapp/action-make-state-repos-dispatches/issues/20
- [ ] https://github.com/prefapp/action-make-state-repos-dispatches/issues/11
- [ ] https://github.com/prefapp/action-make-state-repos-dispatches/issues/2
```
